# https://taskfile.dev
version: '3'

tasks:
  epub:
    sources: 
      - 'us/*.md'
      - ./scripts/gen-epub.pl
    generates: 
      - ./output/trans-travel.epub
    cmds:
      - perl ./scripts/gen-epub.pl
