# https://taskfile.dev
version: '3'

tasks:
  test:
    - prove -Iscripts/lib scripts/t
  epub:
    sources: 
      - t/*.t
      - 'us/*.md'
      - ./scripts/gen-epub.pl
    generates: 
      - ./output/trans-travel.epub
    cmds:
      - perl ./scripts/gen-epub.pl
      # did we do good?
      - { task: test}
